pipeline {
    agent {
        docker{
            image 'ruby'
        }
    }

    stages {
        stage('Preparation'){
            steps{
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
            }
        }
    }
}
